// SPDX-License-Identifier: MIT
// Copyright (c) Robert Vokac and contributors
// Portions based on MonoGame.Extended (MIT License, Copyright (c) Craftwork Games)
//
// CalculateRegionsShouldGenerateUniqueRegionNames is ported from MonoGame.Extended's
// tests/MonoGame.Extended.Tests/Graphics/Texture2DAtlasTests.cs (a regression test for
// https://github.com/MonoGame-Extended/Monogame-Extended/issues/1013: region names generated by
// Create() were not unique). All other tests below are fresh (no other upstream tests exist for
// Texture2DAtlas).
#include "CNA/Extended/Graphics/Texture2DAtlas.hpp"

#include "CNA/Extended/Graphics/Sprite.hpp"
#include "Microsoft/Xna/Framework/Graphics/Texture2D.hpp"

#include <gtest/gtest.h>
#include <limits>
#include <stdexcept>

namespace CNA::Extended::Graphics
{
    namespace
    {
        using Microsoft::Xna::Framework::Graphics::SurfaceFormat;
        using Microsoft::Xna::Framework::Graphics::Texture2D;

        Texture2D MakeTestTexture(int width = 64, int height = 64, const std::string& name = "atlas-texture")
        {
            Texture2D texture = Texture2D::CreateCpuOnlyForTests(width, height, SurfaceFormat::Color,
                std::vector<Color>(static_cast<std::size_t>(width * height), Color::White));
            texture.setNameProperty(name);
            return texture;
        }
    }

    TEST(Texture2DAtlasTests, CalculateRegionsShouldGenerateUniqueRegionNames)
    {
        const std::vector<Texture2DAtlas::CalculatedRegion> regions =
            Texture2DAtlas::CalculateRegions("spritesheet", 64, 64, 32, 32, std::numeric_limits<int>::max(), 0, 0);

        ASSERT_EQ(regions.size(), 4u);
        EXPECT_EQ(regions[0].name, "spritesheet_0");
        EXPECT_EQ(regions[1].name, "spritesheet_1");
        EXPECT_EQ(regions[2].name, "spritesheet_2");
        EXPECT_EQ(regions[3].name, "spritesheet_3");
    }

    TEST(Texture2DAtlasTests, ConstructorGeneratesNameFromTextureWhenEmpty)
    {
        Texture2D texture = MakeTestTexture(64, 64, "my-texture");
        const Texture2DAtlas atlas(&texture);

        EXPECT_EQ(atlas.getNameProperty(), "my-textureAtlas");
        EXPECT_EQ(atlas.getTextureProperty(), &texture);
        EXPECT_EQ(atlas.getRegionCountProperty(), 0);
    }

    TEST(Texture2DAtlasTests, NullTextureThrows)
    {
        EXPECT_THROW((void)Texture2DAtlas(static_cast<Texture2D*>(nullptr)), std::invalid_argument);
    }

    TEST(Texture2DAtlasTests, CreateRegionAddsToBothIndexAndNameLookups)
    {
        Texture2D texture = MakeTestTexture();
        Texture2DAtlas atlas("atlas", &texture);

        const std::shared_ptr<Texture2DRegion> region = atlas.CreateRegion(0, 0, 16, 16, "first");

        EXPECT_EQ(atlas.getRegionCountProperty(), 1);
        EXPECT_EQ(atlas.GetRegion(0), region);
        EXPECT_EQ(atlas.GetRegion("first"), region);
        EXPECT_EQ(atlas[0], region);
        EXPECT_EQ(atlas["first"], region);
        EXPECT_TRUE(atlas.ContainsRegion("first"));
        EXPECT_EQ(atlas.GetIndexOfRegion("first"), 0);
    }

    TEST(Texture2DAtlasTests, CreateRegionDuplicateNameThrows)
    {
        Texture2D texture = MakeTestTexture();
        Texture2DAtlas atlas("atlas", &texture);
        atlas.CreateRegion(0, 0, 16, 16, "dup");

        EXPECT_THROW((void)atlas.CreateRegion(16, 0, 16, 16, "dup"), std::invalid_argument);
    }

    TEST(Texture2DAtlasTests, GetRegionOutOfRangeThrows)
    {
        Texture2D texture = MakeTestTexture();
        const Texture2DAtlas atlas("atlas", &texture);

        EXPECT_THROW((void)atlas.GetRegion(0), std::out_of_range);
    }

    TEST(Texture2DAtlasTests, GetRegionMissingNameThrows)
    {
        Texture2D texture = MakeTestTexture();
        const Texture2DAtlas atlas("atlas", &texture);

        EXPECT_THROW((void)atlas.GetRegion("missing"), System::Collections::Generic::KeyNotFoundException);
    }

    TEST(Texture2DAtlasTests, TryGetRegionByIndexAndName)
    {
        Texture2D texture = MakeTestTexture();
        Texture2DAtlas atlas("atlas", &texture);
        atlas.CreateRegion(0, 0, 8, 8, "one");

        std::shared_ptr<Texture2DRegion> byIndex;
        std::shared_ptr<Texture2DRegion> byName;
        EXPECT_TRUE(atlas.TryGetRegion(0, byIndex));
        EXPECT_TRUE(atlas.TryGetRegion("one", byName));
        EXPECT_EQ(byIndex, byName);

        std::shared_ptr<Texture2DRegion> missing;
        EXPECT_FALSE(atlas.TryGetRegion(5, missing));
        EXPECT_EQ(missing, nullptr);
        EXPECT_FALSE(atlas.TryGetRegion("nope", missing));
    }

    TEST(Texture2DAtlasTests, GetRegionsByIndexesAndNames)
    {
        Texture2D texture = MakeTestTexture();
        Texture2DAtlas atlas("atlas", &texture);
        atlas.CreateRegion(0, 0, 8, 8, "a");
        atlas.CreateRegion(8, 0, 8, 8, "b");
        atlas.CreateRegion(16, 0, 8, 8, "c");

        const std::vector<std::shared_ptr<Texture2DRegion>> byIndex = atlas.GetRegions(std::vector<int>{2, 0});
        ASSERT_EQ(byIndex.size(), 2u);
        EXPECT_EQ(byIndex[0]->getNameProperty(), "c");
        EXPECT_EQ(byIndex[1]->getNameProperty(), "a");

        const std::vector<std::shared_ptr<Texture2DRegion>> byName = atlas.GetRegions(std::vector<std::string>{"b", "a"});
        ASSERT_EQ(byName.size(), 2u);
        EXPECT_EQ(byName[0]->getNameProperty(), "b");
        EXPECT_EQ(byName[1]->getNameProperty(), "a");
    }

    TEST(Texture2DAtlasTests, RemoveRegionByIndexAndName)
    {
        Texture2D texture = MakeTestTexture();
        Texture2DAtlas atlas("atlas", &texture);
        atlas.CreateRegion(0, 0, 8, 8, "a");
        atlas.CreateRegion(8, 0, 8, 8, "b");

        EXPECT_TRUE(atlas.RemoveRegion("a"));
        EXPECT_EQ(atlas.getRegionCountProperty(), 1);
        EXPECT_FALSE(atlas.ContainsRegion("a"));

        EXPECT_TRUE(atlas.RemoveRegion(0));
        EXPECT_EQ(atlas.getRegionCountProperty(), 0);

        EXPECT_FALSE(atlas.RemoveRegion("gone"));
        EXPECT_FALSE(atlas.RemoveRegion(0));
    }

    TEST(Texture2DAtlasTests, ClearRegionsRemovesEverything)
    {
        Texture2D texture = MakeTestTexture();
        Texture2DAtlas atlas("atlas", &texture);
        atlas.CreateRegion(0, 0, 8, 8, "a");
        atlas.CreateRegion(8, 0, 8, 8, "b");

        atlas.ClearRegions();

        EXPECT_EQ(atlas.getRegionCountProperty(), 0);
        EXPECT_FALSE(atlas.ContainsRegion("a"));
    }

    TEST(Texture2DAtlasTests, CreateSpriteByIndexAndName)
    {
        Texture2D texture = MakeTestTexture();
        Texture2DAtlas atlas("atlas", &texture);
        atlas.CreateRegion(0, 0, 8, 8, "a");

        const Sprite byIndex = atlas.CreateSprite(0);
        const Sprite byName = atlas.CreateSprite("a");

        EXPECT_EQ(byIndex.getTextureRegionProperty()->getNameProperty(), "a");
        EXPECT_EQ(byName.getTextureRegionProperty()->getNameProperty(), "a");
    }

    TEST(Texture2DAtlasTests, IteratesRegionsInIndexOrder)
    {
        Texture2D texture = MakeTestTexture();
        Texture2DAtlas atlas("atlas", &texture);
        atlas.CreateRegion(0, 0, 8, 8, "a");
        atlas.CreateRegion(8, 0, 8, 8, "b");
        atlas.CreateRegion(16, 0, 8, 8, "c");

        std::vector<std::string> names;
        for (const std::shared_ptr<Texture2DRegion>& region : atlas)
        {
            names.push_back(region->getNameProperty());
        }

        EXPECT_EQ(names, (std::vector<std::string>{"a", "b", "c"}));
    }

    TEST(Texture2DAtlasTests, CreateDividesTextureIntoGridWithGeneratedNames)
    {
        Texture2D texture = MakeTestTexture(64, 64);
        const Texture2DAtlas atlas = Texture2DAtlas::Create("sheet", &texture, 32, 32);

        EXPECT_EQ(atlas.getRegionCountProperty(), 4);
        EXPECT_TRUE(atlas.ContainsRegion("sheet_0"));
        EXPECT_TRUE(atlas.ContainsRegion("sheet_3"));
        EXPECT_EQ(atlas.GetRegion("sheet_0")->getBoundsProperty(), Rectangle(0, 0, 32, 32));
        EXPECT_EQ(atlas.GetRegion("sheet_1")->getBoundsProperty(), Rectangle(32, 0, 32, 32));
    }

    TEST(Texture2DAtlasTests, CreateRespectsMaxRegionCount)
    {
        Texture2D texture = MakeTestTexture(64, 64);
        const Texture2DAtlas atlas = Texture2DAtlas::Create("sheet", &texture, 32, 32, 2);

        EXPECT_EQ(atlas.getRegionCountProperty(), 2);
    }
}
